language: csharp

dotnet: 3.0
sudo: false

env:
    global:
        - DOTNET_CLI_TELEMETRY_OPTOUT: 1

script:
    - dotnet build LT.sln -c Release
    - dotnet test -c Release --no-build LT.Core.Tests/LT.Core.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    
after_script:
    - bash <(curl -s https://codecov.io/bash)
